const DATA=window.WORK_LIB_DATA||{entries:[]};const entries=DATA.entries||[];const hotTags=["家庭日","EAP","员工活动","宣传设计","AI工具","生物医药","企业文化","方法论","半月刊"];
function $(s){return document.querySelector(s)}function $all(s){return Array.from(document.querySelectorAll(s))}
function rating(n=0){return"★★★★★".slice(0,n)}function href(e){return`article.html?id=${encodeURIComponent(e.id)}`}
function card(e){return`<article class="entry-card"><div class="entry-meta"><span class="entry-type">${e.type}</span><span class="entry-date">${e.date}</span></div><h3>${e.title}</h3><p>${e.summary}</p><div class="entry-tags">${(e.tags||[]).slice(0,4).map(t=>`<span>${t}</span>`).join("")}</div><div class="card-footer"><span class="rating">${rating(e.rating)}</span><a class="read-link" href="${href(e)}">阅读全文 →</a></div></article>`}
function match(e,q="",tag="",type="",cat=""){q=(q||"").toLowerCase().trim();const s=[e.title,e.summary,e.type,e.category,...(e.tags||[]),...(e.keywords||[]),...(e.project||[])].join(" ").toLowerCase();return(!q||s.includes(q))&&(!tag||(e.tags||[]).includes(tag))&&(!type||e.type===type)&&(!cat||e.category===cat)}
function tags(el,onClick){el=typeof el==="string"?$(el):el;if(!el)return;el.innerHTML=hotTags.map(t=>`<button class="quick-tag" data-tag="${t}">#${t}</button>`).join("");el.querySelectorAll(".quick-tag").forEach(b=>b.addEventListener("click",()=>{const on=b.classList.contains("active");el.querySelectorAll(".quick-tag").forEach(x=>x.classList.remove("active"));if(!on)b.classList.add("active");onClick(on?"":b.dataset.tag)}))}
function nav(){const p=document.body.dataset.page;$all(".desktop-nav a").forEach(a=>{if(a.dataset.nav===p)a.classList.add("active")})}
function home(){if(!document.body.classList.contains("home"))return;const t=DATA.today||{};$("#todayTitle").textContent=t.title||"";$("#todayConclusion").textContent=t.conclusion||"";$("#todayTags").innerHTML=(t.tags||[]).map(x=>`<span class="tag">#${x}</span>`).join("");const grid=$("#homeEntryGrid"),input=$("#homeSearchInput");let active="";function update(){const list=entries.filter(e=>match(e,input?input.value:"",active)).slice(0,6);grid.innerHTML=list.length?list.map(card).join(""):`<div class="empty-state">没有找到匹配内容。</div>`}tags("#homeQuickTags",t=>{active=t;update()});input&&input.addEventListener("input",update);update()}
function fill(sel,vals){if(!sel)return;vals.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;sel.appendChild(o)})}
function library(){const grid=$("#libraryEntryGrid");if(!grid)return;const input=$("#librarySearchInput"),type=$("#typeFilter"),cat=$("#categoryFilter"),meta=$("#libraryResultMeta");let active="";fill(type,[...new Set(entries.map(e=>e.type))]);fill(cat,[...new Set(entries.map(e=>e.category))]);function update(){const list=entries.filter(e=>match(e,input?input.value:"",active,type?type.value:"",cat?cat.value:""));grid.innerHTML=list.length?list.map(card).join(""):`<div class="empty-state">没有找到匹配内容。</div>`;meta.textContent=`共找到 ${list.length} 条内容`}tags("#libraryQuickTags",t=>{active=t;update()});[input,type,cat].forEach(el=>{if(el){el.addEventListener("input",update);el.addEventListener("change",update)}});$("#clearFilters")?.addEventListener("click",()=>{if(input)input.value="";if(type)type.value="";if(cat)cat.value="";active="";$all("#libraryQuickTags .quick-tag").forEach(b=>b.classList.remove("active"));update()});update()}
function magazine(){const box=$("#magazineList");if(!box)return;const list=entries.filter(e=>e.type==="半月刊");box.innerHTML=list.map(e=>`<article class="magazine-feature"><div class="magazine-cover"><span>Work-Lib</span><strong>半月刊</strong><span>${e.date}</span></div><div class="magazine-content"><span class="magazine-kicker">Magazine</span><h2>${e.title}</h2><p>${e.summary}</p><div class="entry-tags">${e.tags.slice(0,5).map(t=>`<span>${t}</span>`).join("")}</div><div class="hero-actions"><a class="primary-btn" href="${href(e)}">阅读本期 →</a><a class="ghost-btn" href="library.html">回到内容库</a></div></div></article>`).join("")}
function favorites(){const grid=$("#favoritesGrid");if(!grid)return;grid.innerHTML=entries.filter(e=>(e.rating||0)>=4).sort((a,b)=>b.rating-a.rating||b.date.localeCompare(a.date)).map(card).join("")}
function methods(){const grid=$("#methodsGrid");if(!grid)return;grid.innerHTML=entries.filter(e=>e.type==="方法论"||(e.tags||[]).includes("方法论")).map(card).join("")}
function article(){const shell=$("#articleShell");if(!shell)return;const id=new URLSearchParams(location.search).get("id")||entries[0]?.id;const e=entries.find(x=>x.id===id)||entries[0];if(!e){shell.innerHTML=`<div class="empty-state">没有找到文章。</div>`;return}shell.innerHTML=`<span class="entry-type">${e.type} · ${e.category}</span><h1>${e.title}</h1><p class="article-summary">${e.summary}</p><div class="article-meta-line"><span class="tag">${e.date}</span><span class="tag">${rating(e.rating)}</span>${(e.tags||[]).map(t=>`<span class="tag">#${t}</span>`).join("")}</div><div class="project-row">${(e.project||[]).map(p=>`<span>适合：${p}</span>`).join("")}</div><div class="article-body">${(e.body||[]).map(p=>`<p>${p}</p>`).join("")}</div><div class="hero-actions"><a class="ghost-btn" href="library.html">← 回到内容库</a><a class="ghost-btn" href="favorites.html">查看收藏</a></div>`}
function globalSearch(){const overlay=$("#searchOverlay"),open=$("#openSearch"),close=$("#closeSearch"),input=$("#globalSearchInput"),results=$("#globalSearchResults");if(!overlay||!open)return;let active="";function update(){const list=entries.filter(e=>match(e,input.value,active)).slice(0,8);results.innerHTML=list.length?list.map(e=>`<a class="search-result" href="${href(e)}"><h4>${e.title}</h4><p>${e.summary}</p></a>`).join(""):`<div class="empty-state">没有找到匹配内容。</div>`}open.addEventListener("click",()=>{overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");input.focus();update()});close?.addEventListener("click",()=>{overlay.classList.remove("open")});overlay.addEventListener("click",e=>{if(e.target===overlay)overlay.classList.remove("open")});input.addEventListener("input",update);tags("#globalQuickTags",t=>{active=t;update()})}
document.addEventListener("DOMContentLoaded",()=>{nav();home();library();magazine();favorites();methods();article();globalSearch()});