
const D = window.WORK_LIB_DATA || {};
const issues = D.issues || [];
const magazines = D.magazines || [];
const collections = D.collections || [];
const methods = D.methods || [];
const tags = (D.site && D.site.hotTags) || [];
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
function tagHtml(arr){return (arr||[]).map(t=>`<span class="tag">#${t}</span>`).join("")}
function issueLink(id){return `issue.html?id=${encodeURIComponent(id)}`}
function setNav(){const p=document.body.dataset.page;$$('.top-nav a').forEach(a=>{if(a.dataset.nav===p)a.classList.add('active')})}
function renderHome(){if(document.body.dataset.page!=='home')return;const t=D.today||{};$('#homeTitle').textContent=t.title;$('#homeSummary').textContent=t.summary;$('#homeTags').innerHTML=tagHtml(t.tags);$('#homeIssueLink').href=issueLink(t.id);$('#homeDate').textContent=t.date.slice(5).replace('-',' / ');$('#homeAction').textContent=t.action;$('#homeActionLink').href=issueLink(t.id);$('#homeStats').innerHTML=(D.site.stats||[]).map(s=>`<div class="stat"><strong>${s.value}</strong><span>${s.label} ${s.unit}</span></div>`).join('');$('#homeHotTags').innerHTML=tags.map(t=>`<span class="tag">#${t}</span>`).join('')}
function renderDaily(){const box=$('#dailyList');if(!box)return;box.innerHTML=issues.map(i=>`<article class="issue-card"><div class="meta"><span>${i.date}</span><span>${i.type}</span><span>${i.readTime}</span></div><h2>${i.title}</h2><p class="summary">${i.subtitle}</p><div class="tag-row">${tagHtml(i.tags)}</div><a class="read" href="${issueLink(i.id)}">阅读本期 →</a></article>`).join('')}
function renderIssue(){const box=$('#issueDetail');if(!box)return;const id=new URLSearchParams(location.search).get('id')||issues[0].id;const i=issues.find(x=>x.id===id)||issues[0];box.innerHTML=`<p class="kicker">${i.type} · ${i.date}</p><h1>${i.title}</h1><p class="subtitle">${i.subtitle}</p><div class="tag-row">${tagHtml(i.tags)}</div><div class="quote">${i.conclusion}</div>${i.sections.map(s=>`<section class="section-block"><h2>${s.heading}</h2>${s.items.map(item=>`<div class="section-item"><h3>${item.title}</h3><p>${item.body}</p><p class="takeaway">${item.takeaway}</p></div>`).join('')}</section>`).join('')}<section class="section-block"><h2>今日行动</h2><div class="section-item"><p>${i.action}</p></div></section>`}
function renderMagazine(){const box=$('#magazineList');if(!box)return;box.innerHTML=magazines.map(m=>`<article class="mag-card"><div class="meta"><span>${m.date}</span><span>${m.status}</span></div><h2>${m.title}</h2><p class="summary">${m.summary}</p><div class="tag-row">${tagHtml(m.tags)}</div><a class="read" href="#">等待生成 →</a></article>`).join('')}
function renderCollection(){const box=$('#collectionList');if(!box)return;box.innerHTML=collections.map(c=>`<article class="simple-card"><div class="meta"><span>${c.category}</span></div><h2>${c.title}</h2><p class="summary">${c.summary}</p><div class="tag-row">${tagHtml(c.tags)}</div><a class="read" href="${issueLink(c.source)}">查看来源 →</a></article>`).join('')}
function renderMethods(){const box=$('#methodList');if(!box)return;box.innerHTML=methods.map(m=>`<article class="method-card"><h2>${m.title}</h2><p class="summary">${m.summary}</p><ol>${m.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="tag-row">${tagHtml(m.tags)}</div></article>`).join('')}
function renderSearch(){const input=$('#searchInput'), results=$('#searchResults'), tagBox=$('#searchTags');if(!input)return;let active='';const all=[...issues.map(i=>({...i,kind:'每日简报'})),...collections.map(c=>({...c,kind:'灵感库'})),...methods.map(m=>({...m,kind:'方法论'}))];tagBox.innerHTML=tags.map(t=>`<button data-tag="${t}">#${t}</button>`).join('');function match(x){const q=input.value.toLowerCase().trim();const src=[x.title,x.summary,x.subtitle,x.kind,...(x.tags||[])].join(' ').toLowerCase();return(!q||src.includes(q))&&(!active||(x.tags||[]).includes(active))}function update(){const list=all.filter(match);results.innerHTML=list.map(x=>`<article class="simple-card"><div class="meta"><span>${x.kind}</span></div><h2>${x.title}</h2><p class="summary">${x.summary||x.subtitle}</p><div class="tag-row">${tagHtml(x.tags)}</div></article>`).join('')||'<p>没有找到内容。</p>'}tagBox.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=active===b.dataset.tag?'':b.dataset.tag;tagBox.querySelectorAll('button').forEach(x=>x.classList.remove('active'));if(active)b.classList.add('active');update()});input.oninput=update;update()}
document.addEventListener('DOMContentLoaded',()=>{setNav();renderHome();renderDaily();renderIssue();renderMagazine();renderCollection();renderMethods();renderSearch()});
