
const DB=window.WORK_LIB;const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));const page=document.body.dataset.page;const params=new URLSearchParams(location.search);const NOTE_KEY='worklib_notes_v15';const FAV_KEY='worklib_favs_v15';let currentDocId=null;let pendingSelection=null;let editingNoteId=null;
function escapeHtml(str=''){return String(str).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function tagHtml(tags=[]){return tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}
function miniTags(tags=[]){return `<div class="mini-tags">${tags.slice(0,4).map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div>`}
function issueLink(id){return `issue.html?id=${encodeURIComponent(id)}`}
function allDocs(){return [...(DB.featured||[]).map(x=>({...x,kind:x.kind||'本周精选'})),...(DB.issues||[]).map(x=>({...x,kind:x.type||'每日简报'})),...(DB.magazines||[]).map(x=>({...x,kind:'半月刊'})),...(DB.inspirations||[]).map(x=>({...x,kind:'灵感库'})),...(DB.methods||[]).map(x=>({...x,kind:'方法论'})),...(DB.management||[]).map(x=>({...x,kind:'管理视角'}))]}
function findDoc(id){return allDocs().find(d=>d.id===id)}
function groupBy(arr,fn){return arr.reduce((a,x)=>{const k=fn(x)||'未分类';(a[k]||(a[k]=[])).push(x);return a},{})}
function activeNav(){const map={home:'home',daily:'daily',magazine:'magazine',inspiration:'inspiration',methods:'methods',management:'management'};$$('.top-nav a').forEach(a=>{if(a.dataset.nav===map[page])a.classList.add('active')})}
function getNotes(){try{return JSON.parse(localStorage.getItem(NOTE_KEY)||'[]')}catch(e){return []}}
function setNotes(notes){localStorage.setItem(NOTE_KEY, JSON.stringify(notes))}
function getFavs(){try{return JSON.parse(localStorage.getItem(FAV_KEY)||'[]')}catch(e){return []}}
function setFavs(favs){localStorage.setItem(FAV_KEY, JSON.stringify(favs))}
function showToast(msg){const t=$('#toast');if(!t){alert(msg);return}t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function renderHome(){const issue=(DB.featured||[]).find(x=>x.id===DB.meta.homeFeature)||(DB.featured||[])[0]||DB.issues[0];$('#homeTitle').textContent=issue.title;$('#homeSummary').textContent=issue.summary;$('#homeTags').innerHTML=tagHtml(issue.tags);$('#homeIssueLink').href=issueLink(issue.id);$('#homeWeek').innerHTML=`${DB.meta.week}<br><small>${DB.meta.weekRange}</small>`;$('#homeStatsCard').innerHTML=Object.entries(DB.meta.weeklyStats).map(([k,v])=>`<div><b>${escapeHtml(v)}</b><span>${escapeHtml(k)}</span></div>`).join('');$('#homeNext').textContent=`下次更新：${DB.meta.nextUpdate}`;$('#homeStats').innerHTML=Object.entries(DB.meta.weeklyStats).map(([k,v])=>`<div><b>${escapeHtml(v)}</b><span>${escapeHtml(k)}</span></div>`).join('');$('#homeHotTags').innerHTML=(DB.meta.hotTags||[]).map(t=>`<span>${escapeHtml(t)}</span>`).join('')}
function renderTree(items,getGroup,currentId){const root=$('#treeRoot');if(!root)return;const groups=groupBy(items,getGroup);root.innerHTML=Object.entries(groups).map(([g,docs])=>`<div class="tree-group"><p class="tree-group-title">${escapeHtml(g)}</p>${docs.map(d=>`<a class="tree-link ${d.id===currentId?'active':''}" href="${issueLink(d.id)}"><span class="tree-date">${escapeHtml(d.date?String(d.date).replace('2026-','').replace('2026年',''):(d.period||''))}</span>${escapeHtml(d.title)}</a>`).join('')}</div>`).join('')}
function row(d){return `<a class="doc-row" href="${issueLink(d.id)}"><div class="doc-date">${escapeHtml(d.date||d.period||d.category||'')}<br>${escapeHtml(d.type||d.kind||'')}</div><div><h2 class="doc-title">${escapeHtml(d.title)}</h2><p class="doc-summary">${escapeHtml(d.summary||'')}</p>${miniTags(d.tags||[])}</div><div class="doc-meta">${escapeHtml(d.readTime||'查看')} →</div></a>`}
function normalizeItem(item,kind){return {...item,date:item.date||item.period||item.category,type:item.type||kind,kind}}
function renderList(items,groupFn){renderTree(items,groupFn);$('#contentRoot').innerHTML=`<div class="doc-list">${items.map(row).join('')}</div>`}
function renderManagement(){const items=DB.management.map(x=>normalizeItem(x,'管理视角'));renderTree(items,x=>x.category);const timeline=items.filter(x=>x.category==='动态').sort((a,b)=>String(b.timelineDate||b.date).localeCompare(String(a.timelineDate||a.date)));const timelineHtml=`<div class="timeline-card"><h2>动态时间轴</h2><p>只收公开可核验信息；没有新增就明确标注，不用旧内容凑数。</p><div class="timeline">${timeline.map(x=>`<a href="${issueLink(x.id)}"><b>${escapeHtml(x.timelineDate||x.date)}</b><span>${escapeHtml(x.event||x.title)}</span></a>`).join('')}</div></div>`;const groups=['资料','动态','发言'];const groupHtml=groups.map(g=>{const docs=items.filter(x=>x.category===g);return `<section class="mgmt-block"><h2>${g}</h2><div class="doc-list">${docs.map(row).join('')}</div></section>`}).join('');$('#contentRoot').innerHTML=timelineHtml+groupHtml}
function renderLibrary(){if(page==='daily')renderList(DB.issues,x=>x.month);if(page==='magazine')renderList(DB.magazines.map(x=>normalizeItem(x,'半月刊')),x=>'半月刊');if(page==='inspiration')renderList(DB.inspirations.map(x=>normalizeItem(x,'灵感库')),x=>x.category);if(page==='methods')renderList(DB.methods.map(x=>normalizeItem(x,'方法论')),x=>x.category);if(page==='management')renderManagement()}
function renderSection(sec){let html=`<section class="reader-section"><h2>${escapeHtml(sec.heading)}</h2>`;if(sec.body)html+=sec.body.map(p=>`<p>${escapeHtml(p)}</p>`).join('');if(sec.items)html+=sec.items.map(it=>`<div class="insight-item"><h3>${escapeHtml(it.title)}</h3><p>${escapeHtml(it.body)}</p>${it.takeaway?`<p class="takeaway"><strong>可转化 / 提醒：</strong>${escapeHtml(it.takeaway)}</p>`:''}</div>`).join('');html+=`</section>`;return html}
function renderReader(){const id=params.get('id')||DB.meta.homeFeature;currentDocId=id;const doc=findDoc(id);renderTree(allDocs(),x=>x.kind||x.type||'文档',id);if(!doc){$('#readerRoot').innerHTML='<p class="empty">没有找到这条内容。</p>';return}let sections=doc.sections||[];let sourceHtml='';if(doc.sources&&doc.sources.length)sourceHtml=`<div class="source-list"><strong>资料来源 / 参考线索：</strong>${doc.sources.map(s=>`<p>${escapeHtml(s)}</p>`).join('')}</div>`;$('#readerRoot').innerHTML=`<div class="reader-top"><span class="reader-type">${escapeHtml(doc.kind||doc.type||doc.category||'文档')} · ${escapeHtml(doc.date||doc.period||'')}</span><h1>${escapeHtml(doc.title)}</h1><p class="reader-summary">${escapeHtml(doc.summary||'')}</p><div class="tag-row">${tagHtml(doc.tags||[])}</div>${doc.mainLine?`<p class="takeaway"><strong>主线：</strong>${escapeHtml(doc.mainLine)}</p>`:''}</div>${sections.map(renderSection).join('')}${sourceHtml}`;setupFavorite();setTimeout(applyAnnotations,0)}
function renderSearch(){const input=$('#searchInput'),root=$('#searchResults');const docs=allDocs();function go(q=''){q=q.trim().toLowerCase();const filtered=q?docs.filter(d=>JSON.stringify(d).toLowerCase().includes(q)):docs.slice(0,18);root.innerHTML=filtered.length?`<div class="doc-list">${filtered.map(row).join('')}</div>`:`<p class="empty">没有找到相关内容。</p>`}input.addEventListener('input',()=>go(input.value));go('')}
function renderCollection(){const favs=getFavs();const docs=favs.map(findDoc).filter(Boolean);$('#favoriteRoot').innerHTML=docs.length?`<div class="doc-list">${docs.map(row).join('')}</div>`:'<p class="empty">还没有收藏文章。打开文章后点击“收藏”，这里会显示。</p>'}
function setupFavorite(){const btn=$('#favBtn');if(!btn)return;const update=()=>{const favs=getFavs();btn.textContent=favs.includes(currentDocId)?'★ 已收藏':'☆ 收藏'};btn.onclick=()=>{let favs=getFavs();favs=favs.includes(currentDocId)?favs.filter(x=>x!==currentDocId):[...favs,currentDocId];setFavs(favs);update()};update()}
function setupAnnotationEvents(){const reader=$('#readerRoot'), toolbar=$('#noteToolbar');if(!reader||!toolbar)return;document.addEventListener('selectionchange',()=>{if(page!=='issue')return;const sel=window.getSelection();if(!sel||sel.isCollapsed){toolbar.classList.add('hidden');return}const text=sel.toString().trim();if(!text||text.length<2||!reader.contains(sel.anchorNode)||!reader.contains(sel.focusNode)){toolbar.classList.add('hidden');return}const range=sel.getRangeAt(0);const rect=range.getBoundingClientRect();pendingSelection={text, docId:currentDocId};toolbar.style.left=Math.max(12,rect.left+window.scrollX)+'px';toolbar.style.top=Math.max(12,rect.top+window.scrollY-48)+'px';toolbar.classList.remove('hidden')});$('#makeNoteBtn')?.addEventListener('click',()=>{if(!pendingSelection)return;editingNoteId=null;openNoteModal({quote:pendingSelection.text,note:''})});$('#askAIBtn')?.addEventListener('click',askAI);reader.addEventListener('click',e=>{const mark=e.target.closest('.annotation-mark');if(!mark)return;const note=getNotes().find(n=>n.id===mark.dataset.noteId);if(note){editingNoteId=note.id;openNoteModal(note)}});$('#cancelNoteBtn')?.addEventListener('click',closeNoteModal);$('#saveNoteBtn')?.addEventListener('click',saveCurrentNote);$('#deleteNoteBtn')?.addEventListener('click',deleteCurrentNote);$('#exportNotesBtn')?.addEventListener('click',exportNotes)}
function aiPromptFor(text){const doc=findDoc(currentDocId)||{};return `我正在阅读 Work-Lib 里的这篇文章：\n\n标题：《${doc.title||''}》\n\n我选中的原文是：\n“${text}”\n\n我的问题是：\n请你先用通俗的话解释这段话的核心意思，再结合我的工作和公众号方向，判断它最适合转化到哪 1–2 个场景里。\n\n我的重点场景包括：员工活动、公众号选题、EAP、AI 落地、内部传播、活动复盘。\n\n请不要每个场景都泛泛展开，而是优先选择最相关的场景，做深入拆解：\n1. 这段话真正想表达什么；\n2. 为什么它对我有用；\n3. 可以怎么落地成一个具体做法；\n4. 可以转化成什么公众号选题、活动设计或方法论；\n5. 如果要继续追问，我下一步应该问什么。`}
async function askAI(){if(!pendingSelection)return;const prompt=aiPromptFor(pendingSelection.text);try{await navigator.clipboard.writeText(prompt);showToast('已复制提问，可粘贴到你的 AI 侧栏或对话框。')}catch(e){const ta=document.createElement('textarea');ta.value=prompt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();showToast('已复制提问，可粘贴到你的 AI 侧栏或对话框。')}$('#noteToolbar')?.classList.add('hidden')}
function openNoteModal(note){$('#noteModalTitle').textContent=editingNoteId?'编辑批注':'批注';$('#noteQuote').textContent=note.quote||'';$('#noteText').value=note.note||'';$('#deleteNoteBtn').classList.toggle('hidden',!editingNoteId);$('#noteModal').classList.remove('hidden');$('#noteToolbar').classList.add('hidden');setTimeout(()=>$('#noteText').focus(),50)}
function closeNoteModal(){$('#noteModal').classList.add('hidden');pendingSelection=null;editingNoteId=null;window.getSelection()?.removeAllRanges()}
function saveCurrentNote(){const quote=$('#noteQuote').textContent.trim();const note=$('#noteText').value.trim();if(!quote||!note){alert('请先写下批注内容。');return}let notes=getNotes();if(editingNoteId){notes=notes.map(n=>n.id===editingNoteId?{...n,note,updatedAt:new Date().toISOString()}:n)}else{notes.push({id:'note-'+Date.now()+'-'+Math.random().toString(16).slice(2),docId:currentDocId,quote,note,createdAt:new Date().toISOString()})}setNotes(notes);closeNoteModal();renderReader()}
function deleteCurrentNote(){if(!editingNoteId)return;if(!confirm('删除这条批注吗？'))return;setNotes(getNotes().filter(n=>n.id!==editingNoteId));closeNoteModal();renderReader()}
function exportNotes(){const notes=getNotes();const payload=notes.map(n=>{const doc=findDoc(n.docId)||{};return {...n,docTitle:doc.title||n.docId,docType:doc.kind||doc.type||doc.category||'',docDate:doc.date||doc.period||''}});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='work-lib-批注备份.json';a.click();URL.revokeObjectURL(a.href)}
function applyAnnotations(){const reader=$('#readerRoot');if(!reader)return;const notes=getNotes().filter(n=>n.docId===currentDocId).sort((a,b)=>b.quote.length-a.quote.length);notes.forEach(note=>highlightQuote(reader,note))}
function highlightQuote(root,note){const quote=note.quote;if(!quote)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){if(!node.nodeValue.includes(quote))return NodeFilter.FILTER_REJECT;if(node.parentElement.closest('.annotation-mark'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const node=walker.nextNode();if(!node)return;const text=node.nodeValue;const idx=text.indexOf(quote);if(idx<0)return;const frag=document.createDocumentFragment();frag.append(document.createTextNode(text.slice(0,idx)));const mark=document.createElement('mark');mark.className='annotation-mark';mark.dataset.noteId=note.id;mark.title=note.note;mark.textContent=quote;frag.append(mark);frag.append(document.createTextNode(text.slice(idx+quote.length)));node.parentNode.replaceChild(frag,node)}
activeNav();if(page==='home')renderHome();if(['daily','magazine','inspiration','methods','management'].includes(page))renderLibrary();if(page==='issue'){renderReader();setupAnnotationEvents()}if(page==='search')renderSearch();if(page==='collection')renderCollection();
